site_name: FetalSynthGen

theme:
  name: readthedocs
  logo: media/fetsynthgen_logo.png  # Path to your logo file
  favicon: media/favicon-32x32.pngs  # Path to your favicon file

plugins:
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    handlers:
      python:
        options:
          show_source: false
          members_order: source
          relative_crossrefs: true

        
- search
- autorefs
- awesome-pages