                SignalFillEmptyd(
                    keys=["image", "label"],
                    replacement=0,
                    allow_missing_keys=True,
                ),
                CropForegroundd(
                    keys=["image", "label"],
                    source_key="image",
                    allow_smaller=True,
                    margin=0,
                ),
                Spacingd(
                    keys=["image", "label"],
                    pixdim=(
                        self.rescale_res,
                        self.rescale_res,
                        self.rescale_res,
                    ),
                    mode=("bilinear", "nearest"),
                ),
                SpatialPadd(
                    keys=["image", "label"],
                    spatial_size=(256, 256, 256),
                    mode="constant",
                ),
                CenterSpatialCropd(
                    keys=["image", "label"],
                    roi_size=(256, 256, 256),
                ),
            ]
        )