# # loads by default the transforms from the preprocess.yaml file
# defaults:
#   - preprocess

# TODO: Make different versions for Real/Simple/Synth dataset
_target_: fetalsyngen.dataset.fetal.FetalSynthDataset
bids_path: ./data
seed_path: ./data/derivatives/seeds # TODO: make clear that by setting this to none intensity image wull bee used as intesity prior
sub_list: null
load_image: True
# transforms from the preprocess.yaml file
# can be overridden here
# transforms: null


generator:
  _target_: fetalsyngen.generator.SynthGen

  shape: [256, 256, 256] # TODO: Note that this is input/output
  resolution: [0.5, 0.5, 0.5]
  device: cuda

  image_seed_generator:
    _target_: fetalsyngen.intensity.seed_sampler.ImageFromSeeds
    min_subclusters: 1
    max_subclusters: 3
    seed_labels: [0, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
    # generation_classes: [0, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
    generation_classes: [0, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49] # [0, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49] # ##

  spatial_deform:
    _target_: fetalsyngen.deformation.affine_nonrigid.SpatialDeformation
    size: [256, 256, 256]
    max_rotation: 20
    max_shear: 0.02
    max_scaling: 0.1

    nonlinear_transform: True
    nonlin_scale_min: 0.03
    nonlin_scale_max: 0.06
    nonlin_std_max: 4

  rand_resample:
    _target_: fetalsyngen.augmentation.synthseg_augm.RandResample
    min_resolution: 1.9
    max_resolution: 2
    prob: 0

  rand_biasfield:
    _target_: fetalsyngen.augmentation.synthseg_augm.RandBiasField
    prob: 0
    scale_min: 0.004 
    scale_max: 0.02
    std_min:  0.01
    std_max: 0.3

  rand_gamma:
    _target_: fetalsyngen.augmentation.synthseg_augm.RandGamma
    prob: 0
    gamma_std: 0.1

  rand_noise:
    _target_: fetalsyngen.augmentation.synthseg_augm.RandNoise
    prob: 0
    std_min: 5
    std_max: 15