defaults:
  - generator/default

_target_: fetalsyngen.data.datasets.FetalSynthDataset
bids_path: /media/vzalevskyi/data/fetal_dHCP/derivatives/derivatives/resampled05 #./data
seed_path: /media/vzalevskyi/data/fetal_dHCP/derivatives/derivatives/seeds #./data/derivatives/seeds
sub_list: null
load_image: False
image_as_intensity: False
bids_path_segm_ending: "dseg_CC"

