_target_: fetalsyngen.generator.model.FetalSynthGen

shape: [256, 256, 256] # TODO: Note that this is input/output
resolution: [0.5, 0.5, 0.5]
device: cuda # cuda ~6x faster than cpu

intensity_generator:
  _target_: fetalsyngen.generator.intensity.rand_gmm.ImageFromSeeds
  min_subclusters: 1
  max_subclusters: 3
  seed_labels: [0, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
  # generation_classes: [0, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
  generation_classes: [0, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49] # [0, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49] # ##

spatial_deform:
  _target_: fetalsyngen.generator.deformation.affine_nonrigid.SpatialDeformation
  device: "${..device}" # uses the device from the generator
  size: ${..shape} # uses the shape from the generator
  flip_prb: 0.5

  max_rotation: 20
  max_shear: 0.02
  max_scaling: 0.1

  nonlinear_transform: True
  nonlin_scale_min: 0.03
  nonlin_scale_max: 0.06
  nonlin_std_max: 4

resampler:
  _target_: fetalsyngen.generator.augmentation.synthseg.RandResample
  min_resolution: 1.9
  max_resolution: 2
  prob: 1

bias_field:
  _target_: fetalsyngen.generator.augmentation.synthseg.RandBiasField
  prob: 1
  scale_min: 0.004 
  scale_max: 0.02
  std_min:  0.01
  std_max: 0.3

gamma:
  _target_: fetalsyngen.generator.augmentation.synthseg.RandGamma
  prob: 1
  gamma_std: 0.1

noise:
  _target_: fetalsyngen.generator.augmentation.synthseg.RandNoise
  prob: 1
  std_min: 5
  std_max: 15