defaults:
  # folder: -yaml1 -yaml2 allows for multiple configs to be selected from the workspace
  - augmentation:
    - biasfield
    - gamma
  # folder/yaml when only one config is selected from the workspace
  - deformation/deform
  - intensity/seeds
  - reconstruction/supresolution
  - dataset/bidspaths